format = """
$time\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$openstack\
$env_var\
$crystal\
$lua\

$git_commit\
$git_state\
$git_status\
$jobs\

    $fill\
$cmd_duration\

        $line_break\

$directory\
$git_branch\
$gcloud\

        $line_break\

$username\
$hostname\
${custom.lvl}\
$shell\
$status\
$character\
"""

command_timeout = 500

[character]
success_symbol = "[îŠ…](bold green)"
vicmd_symbol = "[îŠ…](bold yellow)"
error_symbol = "[ï€](bold red)"

[fill]
symbol = " "

[cmd_duration]
min_time = 1_000
style = "#6A6A6A"
format = "[$duration]($style) "

[time]
time_format = "%I:%M%p"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = true

[python]
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'
symbol = "îˆµ "

[nodejs]
symbol = "ï¢˜ "
format = "[$symbol$version]($style) "

[lua]
symbol = "ï†† "
format = "[$symbol$version]($style) "

[cmake]
symbol = "ï¨¶"
format = "[$symbol$version]($style) "

[ruby]
symbol = "îˆ¾ "
format = "[$symbol$version]($style) "

[java]
symbol = "î‰– "
format = "[$symbol$version]($style) "

[perl]
symbol = "î¡/î© "
format = "[$symbol$version]($style) "

[package]
disabled = true

[jobs]
symbol = "ï‰’"
style = "#6A6A6A"
format = "[$symbol (Ã—$number)]($style) "

[git_branch]
symbol = "ï˜ "
format = 'ï„… [$symbol$branch]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "white"
conflicted = "ï«• "
ahead = "ï¤˜Ã—${count} "
behind = "ï¡¶ Ã—${count} "
diverged = "ï¤˜Ã—${ahead_count} ï¡¶ Ã—${behind_count} "
modified = "ï‘ˆ Ã—${count} "
untracked = "ïœ£ Ã—${count} "
stashed = "ïš’ "
staged = "ïœ• ï« Ã—${count} "
renamed = "î‰¼ Ã—${count} "
deleted = "ï’ Ã—${count} "

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style)'
symbol = 'ïƒ‚ '
disabled = true


[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)@"
disabled = true

[hostname]
ssh_only = true
format = "[$hostname](bold red) "
disabled = false

[directory]
truncation_length = 8
read_only = " ï€£"

[directory.substitutions]
"~/projects" = "projects"
"~/Dropbox/uni" = "uni"
".dotfiles" = "dotfiles"

[custom.lvl]
command = "show_sh_lvl"
when = "show_sh_lvl"
style = "#FFA570"
format = "[($output )]($style)"
disabled = true

[shell]
disabled = false
fish_indicator = "ïœ¹ "
zsh_indicator = ""
bash_indicator = "ğ "
xonsh_indicator = "ğ— "
unknown_indicator = "ï„¨ "
format = "$indicator"
