format = """
$time\
$nix_shell\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$conda\
$memory_usage\
$aws\
$openstack\
$env_var\
$crystal\
$lua\

$git_commit\
$git_state\
$git_status\
$jobs\

    $fill\
$cmd_duration\

        $line_break\

$directory\
$git_branch\
$gcloud\

        $line_break\

$username\
$hostname\
${custom.lvl}\
$shell\
$status\
$character\
"""

command_timeout = 500

[character]
success_symbol = "[ó±ª](bold green)"
vicmd_symbol = "[î˜«](bold blue)"
error_symbol = "[ó±˜](bold red)"

[fill]
symbol = " "

[cmd_duration]
min_time = 1_000
style = "#6A6A6A"
format = "[$duration]($style) "

[time]
time_format = "%I:%M%p"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = true

[package]
disabled = true

[jobs]
symbol = "ó±¦Ÿ"
style = "#6A6A6A"
format = "[$symbol (Ã—$number)]($style) "

[git_branch]
symbol = "ó°˜¬ "
format = 'ï„… [$symbol$branch]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "white"
conflicted = "ó°—– "
ahead = "ó°™ Ã—${count} "
behind = "ó°· Ã—${count} "
diverged = "ó°™ Ã—${ahead_count} ó°· Ã—${behind_count} "
modified = "ó°« Ã—${count} "
untracked = "ó°ˆ¤ Ã—${count} "
stashed = "ó°†“ "
staged = "ó°ˆ– Ã—${count} "
renamed = "ó°ˆ Ã—${count} "
deleted = "ó°©¹ Ã—${count} "

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style)'
symbol = 'ïƒ‚ '
disabled = true


[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)@"
disabled = true

[hostname]
ssh_only = true
format = "[$hostname](bold red) "
disabled = false

[directory]
truncation_length = 8
read_only = " ï€£"

[directory.substitutions]
"~/projects" = "projects"
"~/Dropbox/uni" = "uni"
".dotfiles" = "dotfiles"

[custom.lvl]
command = "show_sh_lvl"
when = "show_sh_lvl"
style = "#FFA570"
format = "[($output )]($style)"
disabled = true

[shell]
disabled = false
zsh_indicator = ""
bash_indicator = "ğ "
xonsh_indicator = "ğ— "
unknown_indicator = "ï„¨ "
format = "$indicator"

[nix_shell]
format = '[$symbol$state( \($name\))]($style) '
symbol = 'ïŒ“  '

[python]
symbol = "ó°Œ  "
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "ó°™ "
format = "[$symbol$version]($style) "
style = "bold blue"

[lua]
symbol = "ó°¢± "
format = "[$symbol$version]($style) "

[cmake]
symbol = "ó°”· "
format = "[$symbol$version]($style) "

[ruby]
symbol = "ó°´­ "
format = "[$symbol$version]($style) "

[java]
symbol = "ó°¬· "
format = "[$symbol$version]($style) "

[perl]
symbol = "î¡/î© "
format = "[$symbol$version]($style) "

[rust]
format = "[$symbol($version)]($style) "
version_format = "${raw}"
symbol = "ó±˜— "
style = "bold red"

[golang]
format = "[$symbol($version)]($style) "
symbol = "î˜§ "
style = "bold blue"
